export const UNAUTHORIZED = 'UNAUTHORIZED';
export const USERNAME_OR_PASSWORD_NOT_MATCH = 'USERNAME_OR_PASSWORD_NOT_MATCH';
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
export const PHONE_NUMBER_ALREADY_EXISTS = 'PHONE_NUMBER_ALREADY_EXISTS';
export const NOT_FOUND_STUDENT = 'NOT_FOUND_STUDENT';
